# -*- coding: utf-8 -*-
"""Master Thesis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z64FXbB0N7PFuuDMrXF2Vb4UR8rrmQDA
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns
import shap
import mord
import pickle
import io
import warnings

from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder, label_binarize
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import (
    RandomForestClassifier,
    GradientBoostingClassifier,
    HistGradientBoostingClassifier
)
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report,
    roc_auc_score,
    roc_curve,
    auc,
    mean_absolute_error
)
from scipy.stats import ttest_rel
from imblearn.over_sampling import SMOTE

warnings.filterwarnings('ignore')

# ─────────────────────────────────────────────
# Page configuration
# ─────────────────────────────────────────────
st.set_page_config(
    page_title="Student Performance Predictor",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

st.markdown("""
    <style>
    .main { padding: 0rem 1rem; }
    .stAlert { margin-top: 1rem; }
    h1 { color: #1f77b4; }
    h2 { color: #2ca02c; }
    .metric-card {
        background-color: #f0f2f6;
        padding: 1rem;
        border-radius: 0.5rem;
        margin: 0.5rem 0;
    }
    </style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
# Session state initialisation
# ─────────────────────────────────────────────
for key in ['data', 'models', 'best_model', 'scaler', 'feature_names',
            'label_encoders', 'X_test', 'y_test', 'results']:
    if key not in st.session_state:
        st.session_state[key] = None if key not in ['models', 'label_encoders'] else {}

# ─────────────────────────────────────────────
# Title
# ─────────────────────────────────────────────
st.title("🎓 Student Academic Performance Prediction System")
st.markdown("""
This application uses machine learning and Explainable AI to predict student academic
performance and identify at-risk students for early intervention.
""")

# ─────────────────────────────────────────────
# Sidebar
# ─────────────────────────────────────────────
with st.sidebar:
    st.header("Navigation")
    page = st.radio(
        "Select Page:",
        [
            "📊 Data Upload & EDA",
            "🤖 Model Training",
            "📉 Error Analysis",
            "🔮 Single Prediction",
            "📈 Batch Prediction",
            "💡 Model Insights"
        ]
    )
    st.markdown("---")
    st.markdown("### Grade Classifications")
    st.info("""
    - **0:** High Performance
    - **1:** Above Average
    - **2:** Average
    - **3:** Below Average
    - **4:** At-Risk
    """)

GRADE_LABELS = {
    0: "High Performance",
    1: "Above Average",
    2: "Average",
    3: "Below Average",
    4: "At-Risk"
}

# ═══════════════════════════════════════════════════════════
# PAGE 1 — Data Upload & EDA
# ═══════════════════════════════════════════════════════════
if page == "📊 Data Upload & EDA":
    st.header("📊 Data Upload & Exploratory Data Analysis")

    uploaded_file = st.file_uploader("Upload Student Performance Dataset (CSV)", type=['csv'])

    if uploaded_file is not None:
        try:
            data = pd.read_csv(uploaded_file)
            st.session_state.data = data

            st.success(f"✅ Dataset loaded successfully! Total records: {len(data)}")

            col1, col2, col3, col4 = st.columns(4)
            with col1:
                st.metric("Total Students", len(data))
            with col2:
                st.metric("Features", len(data.columns) - 1)
            with col3:
                st.metric("Missing Values", data.isnull().sum().sum())
            with col4:
                st.metric("Grade Classes", data['GradeClass'].nunique())

            st.subheader("Dataset Preview")
            st.dataframe(data.head(20), use_container_width=True)

            st.subheader("Dataset Statistics")
            st.dataframe(data.describe(), use_container_width=True)

            if data.isnull().sum().sum() > 0:
                st.subheader("Missing Values")
                missing_df = pd.DataFrame({
                    'Column': data.columns,
                    'Missing Count': data.isnull().sum().values,
                    'Missing Percentage': (data.isnull().sum().values / len(data) * 100).round(2)
                })
                st.dataframe(missing_df[missing_df['Missing Count'] > 0], use_container_width=True)

            # ── Class imbalance summary ──
            st.subheader("⚠️ Class Imbalance Overview")
            class_counts = data['GradeClass'].value_counts().sort_index()
            class_pct    = (class_counts / len(data) * 100).round(2)
            imbalance_df = pd.DataFrame({
                'Grade Class': [GRADE_LABELS.get(int(i), str(i)) for i in class_counts.index],
                'Count': class_counts.values,
                'Percentage (%)': class_pct.values
            })
            st.dataframe(imbalance_df, use_container_width=True)
            st.warning(
                "Class 4 (At-Risk) accounts for ~50% of students while Class 0 (High Performance) "
                "is only ~4.5%. SMOTE will be applied during training to correct this imbalance."
            )

            st.subheader("Data Visualisations")
            viz_col1, viz_col2 = st.columns(2)

            with viz_col1:
                grade_dist = data['GradeClass'].value_counts().sort_index()
                fig = px.bar(
                    x=[GRADE_LABELS.get(int(i), str(i)) for i in grade_dist.index],
                    y=grade_dist.values,
                    labels={'x': 'Grade Class', 'y': 'Count'},
                    title='Distribution of Grade Classes',
                    color=grade_dist.values,
                    color_continuous_scale='RdYlGn_r'
                )
                st.plotly_chart(fig, use_container_width=True)

            with viz_col2:
                if 'Gender' in data.columns:
                    gender_dist = data['Gender'].value_counts()
                    fig = px.pie(
                        values=gender_dist.values,
                        names=['Female', 'Male'] if len(gender_dist) == 2 else gender_dist.index,
                        title='Gender Distribution'
                    )
                    st.plotly_chart(fig, use_container_width=True)

            viz_col3, viz_col4 = st.columns(2)
            with viz_col3:
                if 'GPA' in data.columns:
                    fig = px.histogram(data, x='GPA', nbins=30, title='GPA Distribution',
                                       color_discrete_sequence=['#2ca02c'])
                    st.plotly_chart(fig, use_container_width=True)

            with viz_col4:
                if 'StudyTimeWeekly' in data.columns and 'GPA' in data.columns:
                    fig = px.scatter(data, x='StudyTimeWeekly', y='GPA',
                                     color='GradeClass', title='Study Time vs GPA',
                                     labels={'StudyTimeWeekly': 'Study Time (hours/week)'},
                                     color_continuous_scale='RdYlGn_r')
                    st.plotly_chart(fig, use_container_width=True)

            st.subheader("Feature Correlation Heatmap (Key Variables)")
            important_vars = ['GPA', 'StudyTimeWeekly', 'Absences', 'Age',
                              'ParentalEducation', 'ParentalSupport', 'Tutoring',
                              'Extracurricular', 'GradeClass']
            available_vars = [v for v in important_vars if v in data.columns]
            if len(available_vars) > 1:
                corr_matrix = data[available_vars].corr()
                fig = px.imshow(
                    corr_matrix,
                    labels=dict(color="Correlation"),
                    color_continuous_scale='RdBu',
                    aspect="auto",
                    text_auto='.2f',
                    title="Feature Correlation Heatmap"
                )
                fig.update_layout(height=600)
                st.plotly_chart(fig, use_container_width=True)

        except Exception as e:
            st.error(f"Error loading dataset: {str(e)}")
    else:
        st.info("👆 Please upload a CSV file to begin analysis")
        st.markdown("""
        **Expected CSV Format:**
        - StudentID, Age, Gender, Ethnicity, ParentalEducation
        - StudyTimeWeekly, Absences, Tutoring, ParentalSupport
        - Extracurricular, Sports, Music, Volunteering
        - GPA, GradeClass (target variable)
        """)

# ═══════════════════════════════════════════════════════════
# PAGE 2 — Model Training
# ═══════════════════════════════════════════════════════════
elif page == "🤖 Model Training":
    st.header("🤖 Machine Learning Model Training")

    if st.session_state.data is None:
        st.warning("⚠️ Please upload data first in the 'Data Upload & EDA' page")
    else:
        data = st.session_state.data.copy()

        st.subheader("Training Configuration")
        config_col1, config_col2, config_col3 = st.columns(3)

        with config_col1:
            test_size    = st.slider("Test Set Size (%)", 10, 40, 20, 5) / 100
            random_state = st.number_input("Random State", 0, 100, 42)

        with config_col2:
            use_smote     = st.checkbox("Use SMOTE for Imbalanced Data", value=True)
            use_cross_val = st.checkbox("Use Cross-Validation (5-fold)", value=True)
            use_grid      = st.checkbox("Use GridSearchCV Hyperparameter Tuning", value=False)

        with config_col3:
            selected_models = st.multiselect(
                "Select Models to Train",
                ["Logistic Regression", "Ordinal Logistic Regression",
                 "Decision Tree", "Naive Bayes", "KNN",
                 "Random Forest", "Gradient Boosting", "Ordinal Gradient Boosting"],
                default=["Random Forest", "Gradient Boosting",
                         "Ordinal Logistic Regression", "Naive Bayes", "KNN"]
            )

        # ── Hyperparameter search grids ──
        param_grids = {
            "Random Forest": {
                'n_estimators': [50, 100, 200],
                'max_depth': [5, 10, None],
                'min_samples_split': [2, 5, 10]
            },
            "Gradient Boosting": {
                'n_estimators': [50, 100, 200],
                'learning_rate': [0.01, 0.1, 0.2],
                'max_depth': [3, 5, 7]
            },
            "Decision Tree": {
                'max_depth': [5, 10, 15, None],
                'min_samples_split': [2, 5, 10]
            },
            "Logistic Regression": {
                'C': [0.01, 0.1, 1, 10],
                'max_iter': [500, 1000]
            },
            "KNN": {
                'n_neighbors': [3, 5, 7, 11],
                'weights': ['uniform', 'distance']
            }
        }

        if st.button("🚀 Train Models", type="primary"):
            with st.spinner("Training models… This may take a few minutes."):
                try:
                    X = data.drop(['StudentID', 'GradeClass'], axis=1, errors='ignore')
                    y = data['GradeClass']

                    st.session_state.feature_names = X.columns.tolist()

                    X_train, X_test, y_train, y_test = train_test_split(
                        X, y, test_size=test_size, random_state=random_state, stratify=y
                    )
                    st.session_state.X_test = X_test
                    st.session_state.y_test  = y_test

                    scaler = StandardScaler()
                    X_train_scaled = scaler.fit_transform(X_train)
                    X_test_scaled  = scaler.transform(X_test)
                    st.session_state.scaler = scaler

                    # ── SMOTE ──
                    X_train_no_smote = X_train_scaled.copy()
                    y_train_no_smote = y_train.copy()

                    if use_smote:
                        smote = SMOTE(random_state=random_state)
                        X_train_scaled, y_train = smote.fit_resample(X_train_scaled, y_train)
                        st.info(f"✅ SMOTE applied. Training size: {len(X_train_no_smote)} → {len(X_train_scaled)}")

                    # ── Model configs ──
                    model_configs = {
                        "Logistic Regression":
                            LogisticRegression(max_iter=1000, random_state=random_state),
                        "Ordinal Logistic Regression":
                            mord.LogisticAT(alpha=1.0, max_iter=1000),
                        "Decision Tree":
                            DecisionTreeClassifier(random_state=random_state, max_depth=10),
                        "Naive Bayes":
                            GaussianNB(),
                        "KNN":
                            KNeighborsClassifier(n_neighbors=5),
                        "Random Forest":
                            RandomForestClassifier(n_estimators=100, random_state=random_state, n_jobs=-1),
                        "Gradient Boosting":
                            GradientBoostingClassifier(n_estimators=100, random_state=random_state),
                        "Ordinal Gradient Boosting":
                            HistGradientBoostingClassifier(random_state=random_state)
                    }

                    results      = {}
                    models_dict  = {}
                    tuning_info  = {}

                    progress_bar = st.progress(0)
                    status_text  = st.empty()

                    for idx, model_name in enumerate(selected_models):
                        status_text.text(f"Training {model_name}…")
                        model = model_configs[model_name]
                        is_ordinal = model_name == "Ordinal Logistic Regression"
                        y_tr = y_train.astype(int) if is_ordinal else y_train

                        # ── GridSearchCV ──
                        if use_grid and model_name in param_grids:
                            gs = GridSearchCV(
                                model, param_grids[model_name],
                                cv=5, scoring='f1_weighted', n_jobs=-1
                            )
                            gs.fit(X_train_scaled, y_tr)
                            model = gs.best_estimator_
                            tuning_info[model_name] = gs.best_params_
                            st.write(f"**{model_name} best params:** {gs.best_params_}")
                        else:
                            model.fit(X_train_scaled, y_tr)

                        y_pred = model.predict(X_test_scaled)
                        y_pred_proba = (model.predict_proba(X_test_scaled)
                                        if hasattr(model, 'predict_proba') else None)

                        # ── Metrics ──
                        acc        = accuracy_score(y_test, y_pred)
                        prec_w     = precision_score(y_test, y_pred, average='weighted', zero_division=0)
                        rec_w      = recall_score(y_test, y_pred, average='weighted', zero_division=0)
                        f1_w       = f1_score(y_test, y_pred, average='weighted', zero_division=0)
                        prec_m     = precision_score(y_test, y_pred, average='macro', zero_division=0)
                        rec_m      = recall_score(y_test, y_pred, average='macro', zero_division=0)
                        f1_m       = f1_score(y_test, y_pred, average='macro', zero_division=0)
                        mae        = mean_absolute_error(y_test, y_pred)

                        # ── Cross-validation ──
                        cv_mean = cv_std = None
                        if use_cross_val:
                            y_cv = y_train.astype(int) if is_ordinal else y_train
                            cv_s = cross_val_score(model, X_train_scaled, y_cv,
                                                   cv=5, scoring='f1_weighted')
                            cv_mean, cv_std = cv_s.mean(), cv_s.std()

                        results[model_name] = {
                            'accuracy': acc,
                            'precision_weighted': prec_w,
                            'recall_weighted': rec_w,
                            'f1_weighted': f1_w,
                            'precision_macro': prec_m,
                            'recall_macro': rec_m,
                            'f1_macro': f1_m,
                            'mae': mae,
                            'cv_mean': cv_mean,
                            'cv_std': cv_std,
                            'confusion_matrix': confusion_matrix(y_test, y_pred),
                            'y_pred': y_pred,
                            'y_pred_proba': y_pred_proba
                        }
                        models_dict[model_name] = model
                        progress_bar.progress((idx + 1) / len(selected_models))

                    st.session_state.models  = models_dict
                    st.session_state.results = results

                    best_model_name = max(results, key=lambda x: results[x]['f1_weighted'])
                    st.session_state.best_model = models_dict[best_model_name]

                    status_text.empty()
                    progress_bar.empty()
                    st.success(f"✅ Training complete! Best model: **{best_model_name}**")

                    # ── SMOTE before/after comparison ──
                    if use_smote:
                        st.subheader("📊 SMOTE Impact Analysis")
                        smote_results = {}
                        for model_name in selected_models:
                            m_no = model_configs[model_name]
                            is_ord = model_name == "Ordinal Logistic Regression"
                            y_ns = y_train_no_smote.astype(int) if is_ord else y_train_no_smote
                            try:
                                m_no.fit(X_train_no_smote, y_ns)
                                yp = m_no.predict(X_test_scaled)
                                smote_results[model_name] = {
                                    'without_smote_f1': f1_score(y_test, yp, average='weighted', zero_division=0),
                                    'without_smote_recall_macro': recall_score(y_test, yp, average='macro', zero_division=0),
                                    'with_smote_f1': results[model_name]['f1_weighted'],
                                    'with_smote_recall_macro': results[model_name]['recall_macro']
                                }
                            except Exception:
                                pass

                        smote_df = pd.DataFrame([{
                            'Model': m,
                            'F1 Without SMOTE': f"{v['without_smote_f1']:.3f}",
                            'F1 With SMOTE': f"{v['with_smote_f1']:.3f}",
                            'Macro Recall Without': f"{v['without_smote_recall_macro']:.3f}",
                            'Macro Recall With': f"{v['with_smote_recall_macro']:.3f}"
                        } for m, v in smote_results.items()])
                        st.dataframe(smote_df, use_container_width=True)
                        st.caption(
                            "SMOTE improves minority class recall by synthetically oversampling "
                            "underrepresented classes in feature space before training."
                        )

                    # ── Metrics table ──
                    st.subheader("Model Performance Comparison")
                    metrics_df = pd.DataFrame([{
                        'Model': m,
                        'Accuracy': f"{results[m]['accuracy']:.3f}",
                        'F1 Weighted': f"{results[m]['f1_weighted']:.3f}",
                        'F1 Macro': f"{results[m]['f1_macro']:.3f}",
                        'Recall Macro': f"{results[m]['recall_macro']:.3f}",
                        'MAE': f"{results[m]['mae']:.3f}",
                        'CV Mean ± Std': (
                            f"{results[m]['cv_mean']:.3f} ± {results[m]['cv_std']:.3f}"
                            if results[m]['cv_mean'] is not None else "N/A"
                        )
                    } for m in results])
                    st.dataframe(metrics_df, use_container_width=True)

                    st.caption(
                        "**F1 Weighted** is inflated by the majority class (Class 4 = 50.6%). "
                        "**F1 Macro** treats all classes equally and is a more honest metric. "
                        "**MAE** captures ordinal distance — predicting Class 0 as Class 4 "
                        "is penalised 4× more than a one-class error."
                    )

                    # ── Statistical significance test ──
                    if use_cross_val and "Random Forest" in results and "Gradient Boosting" in results:
                        st.subheader("📐 Statistical Significance Test (GB vs Random Forest)")
                        gb_cv = cross_val_score(
                            models_dict["Gradient Boosting"], X_train_scaled, y_train,
                            cv=5, scoring='f1_weighted'
                        )
                        rf_cv = cross_val_score(
                            models_dict["Random Forest"], X_train_scaled, y_train,
                            cv=5, scoring='f1_weighted'
                        )
                        t_stat, p_value = ttest_rel(gb_cv, rf_cv)
                        sig = "✅ Statistically significant (p < 0.05)" if p_value < 0.05 \
                              else "⚠️ NOT statistically significant (p ≥ 0.05)"
                        st.metric("t-statistic", f"{t_stat:.4f}")
                        st.metric("p-value", f"{p_value:.4f}")
                        st.info(sig)
                        if p_value >= 0.05:
                            st.warning(
                                "The difference between Gradient Boosting and Random Forest is not "
                                "statistically significant. Claims of superiority should be made cautiously."
                            )

                    # ── Hyperparameter tuning summary ──
                    if tuning_info:
                        st.subheader("🔧 Hyperparameter Tuning Results")
                        rows = []
                        for model_name, params in tuning_info.items():
                            for param, value in params.items():
                                search_range = str(param_grids.get(model_name, {}).get(param, "N/A"))
                                rows.append({
                                    'Model': model_name,
                                    'Parameter': param,
                                    'Search Range': search_range,
                                    'Selected Value': str(value)
                                })
                        st.dataframe(pd.DataFrame(rows), use_container_width=True)

                    # ── Confusion matrix for best model ──
                    st.subheader(f"Confusion Matrix — {best_model_name}")
                    cm = results[best_model_name]['confusion_matrix']
                    fig = px.imshow(
                        cm,
                        labels=dict(x="Predicted", y="Actual", color="Count"),
                        x=[GRADE_LABELS[i] for i in range(cm.shape[1])],
                        y=[GRADE_LABELS[i] for i in range(cm.shape[0])],
                        color_continuous_scale='Blues',
                        title=f'Confusion Matrix — {best_model_name}',
                        text_auto=True
                    )
                    st.plotly_chart(fig, use_container_width=True)

                    # ── Per-class recall ──
                    st.subheader("Per-Class Recall Analysis")
                    y_pred_best = results[best_model_name]['y_pred']
                    report      = classification_report(y_test, y_pred_best, output_dict=True)
                    report_df   = pd.DataFrame(report).transpose()
                    st.dataframe(report_df, use_container_width=True)

                    per_class_recall = []
                    for cls in sorted(y_test.unique()):
                        cls_int = int(cls)
                        # sklearn may store keys as '0', '0.0', or '4', '4.0'
                        # try both int string and float string
                        key = None
                        for candidate in [str(cls_int), str(float(cls_int))]:
                            if candidate in report:
                                key = candidate
                                break
                        if key is not None:
                            per_class_recall.append({
                                'Grade Class': GRADE_LABELS.get(cls_int, str(cls_int)),
                                'Recall': round(report[key]['recall'], 3),
                                'Support': int(report[key]['support'])
                            })

                    if per_class_recall:
                        recall_df = pd.DataFrame(per_class_recall)
                        fig = px.bar(
                            recall_df, x='Grade Class', y='Recall',
                            title='Per-Class Recall (with support count)',
                            text='Support', color='Recall',
                            color_continuous_scale='RdYlGn',
                            range_y=[0, 1]
                        )
                        st.plotly_chart(fig, use_container_width=True)
                    else:
                        st.warning("Could not extract per-class recall. Check classification report keys.")
                    st.caption(
                        "Macro recall averages recall equally across all classes. "
                        "Class 0 (High Performance) typically has the lowest recall due to "
                        "severe underrepresentation (only ~4.5% of data)."
                    )

                    # ── Ablation study ──
                    st.subheader("🔬 Ablation Study")
                    st.markdown(
                        "Each component is disabled one at a time to measure its contribution."
                    )
                    ablation_rows = []

                    # Full system (already computed)
                    # Use float key '4.0' or int key '4' depending on sklearn version
                    cls4_key = '4' if '4' in report else '4.0' if '4.0' in report else None
                    cls4_recall_full = report.get(cls4_key, {}).get('recall', 0) if cls4_key else 0

                    ablation_rows.append({
                        'Configuration': 'Full System',
                        'F1 Weighted': f"{results[best_model_name]['f1_weighted']:.3f}",
                        'F1 Macro': f"{results[best_model_name]['f1_macro']:.3f}",
                        'MAE': f"{results[best_model_name]['mae']:.3f}",
                        'Class 4 Recall': f"{cls4_recall_full:.3f}"
                    })

                    # Without SMOTE
                    try:
                        m_abl = model_configs[best_model_name]
                        m_abl.fit(X_train_no_smote,
                                  y_train_no_smote.astype(int)
                                  if best_model_name == "Ordinal Logistic Regression"
                                  else y_train_no_smote)
                        yp_abl   = m_abl.predict(X_test_scaled)
                        rpt_abl  = classification_report(y_test, yp_abl, output_dict=True)
                        ablation_rows.append({
                            'Configuration': 'Without SMOTE',
                            'F1 Weighted': f"{f1_score(y_test, yp_abl, average='weighted', zero_division=0):.3f}",
                            'F1 Macro': f"{f1_score(y_test, yp_abl, average='macro', zero_division=0):.3f}",
                            'MAE': f"{mean_absolute_error(y_test, yp_abl):.3f}",
                            'Class 4 Recall': f"{rpt_abl.get('4', {}).get('recall', 0):.3f}"
                        })
                    except Exception:
                        pass

                    # Without scaling
                    try:
                        m_abl2 = model_configs[best_model_name]
                        m_abl2.fit(X_train.values,
                                   y_train_no_smote.astype(int)
                                   if best_model_name == "Ordinal Logistic Regression"
                                   else y_train_no_smote)
                        yp_abl2  = m_abl2.predict(X_test.values)
                        rpt_abl2 = classification_report(y_test, yp_abl2, output_dict=True)
                        ablation_rows.append({
                            'Configuration': 'Without Scaling',
                            'F1 Weighted': f"{f1_score(y_test, yp_abl2, average='weighted', zero_division=0):.3f}",
                            'F1 Macro': f"{f1_score(y_test, yp_abl2, average='macro', zero_division=0):.3f}",
                            'MAE': f"{mean_absolute_error(y_test, yp_abl2):.3f}",
                            'Class 4 Recall': f"{rpt_abl2.get('4', {}).get('recall', 0):.3f}"
                        })
                    except Exception:
                        pass

                    # Top-5 features only (by variance as proxy)
                    try:
                        top5_idx = np.argsort(np.var(X_train_scaled, axis=0))[-5:]
                        m_abl3   = model_configs[best_model_name]
                        m_abl3.fit(X_train_scaled[:, top5_idx],
                                   y_train.astype(int)
                                   if best_model_name == "Ordinal Logistic Regression"
                                   else y_train)
                        yp_abl3  = m_abl3.predict(X_test_scaled[:, top5_idx])
                        rpt_abl3 = classification_report(y_test, yp_abl3, output_dict=True)
                        ablation_rows.append({
                            'Configuration': 'Top-5 Features Only',
                            'F1 Weighted': f"{f1_score(y_test, yp_abl3, average='weighted', zero_division=0):.3f}",
                            'F1 Macro': f"{f1_score(y_test, yp_abl3, average='macro', zero_division=0):.3f}",
                            'MAE': f"{mean_absolute_error(y_test, yp_abl3):.3f}",
                            'Class 4 Recall': f"{rpt_abl3.get('4', {}).get('recall', 0):.3f}"
                        })
                    except Exception:
                        pass

                    st.dataframe(pd.DataFrame(ablation_rows), use_container_width=True)
                    st.caption(
                        "Each row disables one component. Comparing with the Full System row "
                        "shows the individual contribution of SMOTE, feature scaling, and feature selection."
                    )

                    # ── Download model ──
                    st.subheader("Save Best Model")
                    model_data = {
                        'model': st.session_state.best_model,
                        'scaler': st.session_state.scaler,
                        'feature_names': st.session_state.feature_names
                    }
                    buffer = io.BytesIO()
                    pickle.dump(model_data, buffer)
                    buffer.seek(0)
                    st.download_button(
                        "📥 Download Best Model",
                        buffer,
                        f"student_model_{best_model_name.replace(' ', '_').lower()}.pkl",
                        "application/octet-stream"
                    )

                except Exception as e:
                    st.error(f"Error during training: {str(e)}")
                    st.exception(e)

# ═══════════════════════════════════════════════════════════
# PAGE 3 — Error Analysis
# ═══════════════════════════════════════════════════════════
elif page == "📉 Error Analysis":
    st.header("📉 Dedicated Error Analysis")

    if st.session_state.best_model is None or st.session_state.results is None:
        st.warning("⚠️ Please train models first in the 'Model Training' page")
    else:
        results      = st.session_state.results
        models_dict  = st.session_state.models
        X_test       = st.session_state.X_test
        y_test       = st.session_state.y_test
        scaler       = st.session_state.scaler
        feature_names = st.session_state.feature_names

        model_name   = st.selectbox("Select Model for Error Analysis", list(models_dict.keys()))
        model        = models_dict[model_name]
        X_test_scaled = scaler.transform(X_test)
        y_pred        = model.predict(X_test_scaled)

        # ── Overall error summary ──
        total      = len(y_test)
        correct    = (y_test.values == y_pred).sum()
        incorrect  = total - correct
        st.subheader("📊 Overall Error Summary")
        e1, e2, e3 = st.columns(3)
        e1.metric("Total Test Samples", total)
        e2.metric("Correct Predictions", correct, f"{correct/total*100:.1f}%")
        e3.metric("Misclassified", incorrect, f"{incorrect/total*100:.1f}%")

        # ── Misclassified students table ──
        st.subheader("🔍 Misclassified Students — Example Cases")
        misclassified_df = X_test.copy()
        misclassified_df['True_Class']      = y_test.values
        misclassified_df['Predicted_Class'] = y_pred
        misclassified_df['True_Label']      = misclassified_df['True_Class'].apply(
            lambda x: GRADE_LABELS.get(int(x), str(x))
        )
        misclassified_df['Predicted_Label'] = misclassified_df['Predicted_Class'].apply(
            lambda x: GRADE_LABELS.get(int(x), str(x))
        )
        misclassified_df['Ordinal_Error']   = abs(
            misclassified_df['True_Class'].astype(int) -
            misclassified_df['Predicted_Class'].astype(int)
        )

        only_wrong = misclassified_df[
            misclassified_df['True_Class'] != misclassified_df['Predicted_Class']
        ].sort_values('Ordinal_Error', ascending=False)

        st.markdown(f"**Total misclassified: {len(only_wrong)} out of {total} students**")
        st.dataframe(only_wrong.head(20), use_container_width=True)

        # ── Ordinal error distribution ──
        st.subheader("📏 Ordinal Error Distribution")
        st.markdown(
            "Ordinal error = |True Class − Predicted Class|. "
            "An error of 1 means the model was off by one grade level. "
            "An error of 4 (predicting Class 0 as Class 4) is the worst possible."
        )
        err_counts = only_wrong['Ordinal_Error'].value_counts().sort_index()
        fig = px.bar(
            x=err_counts.index, y=err_counts.values,
            labels={'x': 'Ordinal Error Magnitude', 'y': 'Number of Students'},
            title='Distribution of Ordinal Errors',
            color=err_counts.values,
            color_continuous_scale='Reds'
        )
        st.plotly_chart(fig, use_container_width=True)

        # ── Class 0 false negatives analysis ──
        st.subheader("⚠️ Why Does the Model Struggle with Class 0 (High Performance)?")
        class0_true = misclassified_df[misclassified_df['True_Class'] == 0]
        class0_fn   = class0_true[class0_true['Predicted_Class'] != 0]

        st.markdown(f"""
        - **Class 0 students in test set:** {len(class0_true)}
        - **Class 0 correctly predicted:** {len(class0_true) - len(class0_fn)}
        - **Class 0 false negatives (missed):** {len(class0_fn)}
        """)

        if len(class0_fn) > 0:
            st.markdown("**Example Class 0 students that were misclassified:**")
            st.dataframe(class0_fn.head(10), use_container_width=True)

        st.info("""
        **Why Class 0 has high false negatives:**
        1. Class 0 represents only ~4.5% of the dataset (107 students). Even with SMOTE,
           synthetic samples may not fully capture the true decision boundary.
        2. High-performing students (Class 0) and above-average students (Class 1) often
           share similar GPA ranges, making the boundary inherently ambiguous.
        3. The model is optimised for recall on Class 4 (at-risk), which can slightly
           deprioritise precision on the minority high-performance class.
        """)

        # ── Per-class error breakdown ──
        st.subheader("Per-Class Error Breakdown")
        class_error_rows = []
        for cls in sorted(y_test.unique()):
            cls_int   = int(cls)
            true_mask = misclassified_df['True_Class'] == cls
            fn        = misclassified_df[true_mask & (misclassified_df['Predicted_Class'] != cls)]
            tp        = misclassified_df[true_mask & (misclassified_df['Predicted_Class'] == cls)]
            class_error_rows.append({
                'Class': GRADE_LABELS.get(cls_int, str(cls_int)),
                'Total True': true_mask.sum(),
                'Correctly Predicted': len(tp),
                'Misclassified': len(fn),
                'Error Rate (%)': f"{len(fn)/true_mask.sum()*100:.1f}" if true_mask.sum() > 0 else "0.0"
            })
        st.dataframe(pd.DataFrame(class_error_rows), use_container_width=True)

# ═══════════════════════════════════════════════════════════
# PAGE 4 — Single Prediction
# ═══════════════════════════════════════════════════════════
elif page == "🔮 Single Prediction":
    st.header("🔮 Single Student Prediction")

    if st.session_state.best_model is None:
        st.warning("⚠️ Please train a model first in the 'Model Training' page")
    else:
        st.markdown("Enter student information to predict academic performance:")

        col1, col2, col3 = st.columns(3)
        with col1:
            age                = st.number_input("Age", 15, 20, 17)
            gender             = st.selectbox("Gender", [0, 1], format_func=lambda x: "Female" if x == 0 else "Male")
            ethnicity          = st.selectbox("Ethnicity", [0, 1, 2, 3])
            parental_education = st.selectbox("Parental Education", [0, 1, 2, 3, 4])

        with col2:
            study_time      = st.number_input("Study Time (hours/week)", 0.0, 30.0, 10.0, 0.5)
            absences        = st.number_input("Absences", 0, 30, 5)
            tutoring        = st.selectbox("Tutoring", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
            parental_support = st.selectbox("Parental Support", [0, 1, 2, 3, 4])

        with col3:
            extracurricular = st.selectbox("Extracurricular", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
            sports          = st.selectbox("Sports", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
            music           = st.selectbox("Music", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
            volunteering    = st.selectbox("Volunteering", [0, 1], format_func=lambda x: "No" if x == 0 else "Yes")
            gpa             = st.number_input("GPA", 0.0, 4.0, 2.5, 0.01)

        if st.button("🔮 Predict Performance", type="primary"):
            try:
                input_data = pd.DataFrame({
                    'Age': [age], 'Gender': [gender], 'Ethnicity': [ethnicity],
                    'ParentalEducation': [parental_education],
                    'StudyTimeWeekly': [study_time], 'Absences': [absences],
                    'Tutoring': [tutoring], 'ParentalSupport': [parental_support],
                    'Extracurricular': [extracurricular], 'Sports': [sports],
                    'Music': [music], 'Volunteering': [volunteering], 'GPA': [gpa]
                })

                input_scaled = st.session_state.scaler.transform(input_data)
                prediction   = int(st.session_state.best_model.predict(input_scaled)[0])
                pred_proba   = (st.session_state.best_model.predict_proba(input_scaled)[0]
                                if hasattr(st.session_state.best_model, 'predict_proba') else None)

                st.success("✅ Prediction Complete!")

                res_col1, res_col2 = st.columns([1, 2])
                with res_col1:
                    st.markdown(f"### Predicted Grade: **{GRADE_LABELS.get(prediction, 'Unknown')}**")
                    st.markdown(f"### Class: **{prediction}**")
                    if prediction >= 3:
                        st.error("⚠️ AT-RISK — Immediate intervention recommended!")
                    elif prediction == 2:
                        st.warning("⚠️ Average performance — Monitoring recommended.")
                    else:
                        st.success("✅ Performing well!")

                with res_col2:
                    if pred_proba is not None:
                        prob_df = pd.DataFrame({
                            'Grade Class': [GRADE_LABELS[i] for i in range(len(pred_proba))],
                            'Probability': pred_proba
                        })
                        fig = px.bar(prob_df, x='Grade Class', y='Probability',
                                     title='Prediction Probability Distribution',
                                     color='Probability',
                                     color_continuous_scale='RdYlGn_r')
                        fig.update_layout(yaxis=dict(range=[0, 1]))
                        st.plotly_chart(fig, use_container_width=True)
                    else:
                        st.info("Probability distribution not available for Ordinal Logistic Regression.")

                # ── SHAP explanation ──
                st.subheader("🔍 Prediction Explanation (SHAP)")
                with st.spinner("Generating SHAP values…"):
                    try:
                        # KernelExplainer works universally for all model types
                        # including GradientBoostingClassifier multiclass
                        background = shap.sample(
                            st.session_state.scaler.transform(
                                st.session_state.X_test
                            ), min(30, len(st.session_state.X_test))
                        )
                        predict_fn = (st.session_state.best_model.predict_proba
                                      if hasattr(st.session_state.best_model, 'predict_proba')
                                      else st.session_state.best_model.predict)
                        explainer   = shap.KernelExplainer(predict_fn, background)
                        shap_values = explainer.shap_values(input_scaled)

                        # For multiclass, shap_values is a list (one array per class)
                        # Use the predicted class index to show class-specific explanation
                        if isinstance(shap_values, list):
                            sv = shap_values[prediction][0]
                        else:
                            sv = shap_values[0]

                        feature_imp = pd.DataFrame({
                            'Feature': st.session_state.feature_names,
                            'SHAP Value': sv
                        }).sort_values('SHAP Value', ascending=True)

                        fig, ax = plt.subplots(figsize=(10, 6))
                        colors = ['#d73027' if v > 0 else '#4575b4'
                                  for v in feature_imp['SHAP Value']]
                        ax.barh(feature_imp['Feature'], feature_imp['SHAP Value'],
                                color=colors)
                        ax.axvline(x=0, color='black', linewidth=0.8)
                        ax.set_xlabel('SHAP Value (positive = pushes toward higher risk class)')
                        ax.set_title(f'Feature Contributions — Predicted: {GRADE_LABELS.get(prediction)}')
                        plt.tight_layout()
                        st.pyplot(fig)
                        plt.close()
                        st.caption(
                            "Red bars push the prediction toward a higher (worse) grade class. "
                            "Blue bars push toward a lower (better) grade class."
                        )
                    except Exception as e:
                        st.warning(f"SHAP visualisation not available: {str(e)}")

            except Exception as e:
                st.error(f"Error during prediction: {str(e)}")
                st.exception(e)

# ═══════════════════════════════════════════════════════════
# PAGE 5 — Batch Prediction
# ═══════════════════════════════════════════════════════════
elif page == "📈 Batch Prediction":
    st.header("📈 Batch Prediction")

    if st.session_state.best_model is None:
        st.warning("⚠️ Please train a model first in the 'Model Training' page")
    else:
        batch_file = st.file_uploader("Upload Student Data (CSV)", type=['csv'], key='batch')

        if batch_file is not None:
            try:
                batch_data = pd.read_csv(batch_file)
                st.success(f"✅ File loaded! Total students: {len(batch_data)}")
                st.dataframe(batch_data.head(), use_container_width=True)

                if st.button("🚀 Generate Predictions", type="primary"):
                    with st.spinner("Generating predictions…"):
                        batch_X        = batch_data.drop(['StudentID', 'GradeClass'], axis=1, errors='ignore')
                        batch_X_scaled = st.session_state.scaler.transform(batch_X)
                        predictions    = st.session_state.best_model.predict(batch_X_scaled)
                        pred_proba     = (st.session_state.best_model.predict_proba(batch_X_scaled)
                                          if hasattr(st.session_state.best_model, 'predict_proba') else None)

                        result_df = batch_data.copy()
                        result_df['Predicted_GradeClass'] = predictions.astype(int)
                        result_df['Predicted_Label']      = result_df['Predicted_GradeClass'].map(GRADE_LABELS)
                        if pred_proba is not None:
                            result_df['Confidence'] = pred_proba.max(axis=1)
                        else:
                            result_df['Confidence'] = 'N/A'

                        st.success("✅ Predictions generated!")

                        s1, s2, s3, s4 = st.columns(4)
                        at_risk = (predictions >= 3).sum()
                        avg_p   = (predictions == 2).sum()
                        good    = (predictions <= 1).sum()
                        s1.metric("At-Risk Students", at_risk, f"{at_risk/len(predictions)*100:.1f}%")
                        s2.metric("Average Performance", avg_p, f"{avg_p/len(predictions)*100:.1f}%")
                        s3.metric("Good Performance", good, f"{good/len(predictions)*100:.1f}%")
                        if pred_proba is not None:
                            s4.metric("Avg Confidence", f"{pred_proba.max(axis=1).mean():.2%}")

                        st.dataframe(result_df, use_container_width=True)

                        at_risk_df = result_df[result_df['Predicted_GradeClass'] >= 3]
                        if len(at_risk_df) > 0:
                            st.subheader("⚠️ At-Risk Students")
                            st.dataframe(at_risk_df, use_container_width=True)

                        csv = result_df.to_csv(index=False).encode('utf-8')
                        st.download_button("📥 Download Predictions CSV", csv,
                                           "student_predictions.csv", "text/csv")

            except Exception as e:
                st.error(f"Error: {str(e)}")
                st.exception(e)

# ═══════════════════════════════════════════════════════════
# PAGE 6 — Model Insights
# ═══════════════════════════════════════════════════════════
elif page == "💡 Model Insights":
    st.header("💡 Model Insights & Explainable AI")

    if not st.session_state.models:
        st.warning("⚠️ Please train models first in the 'Model Training' page")
    else:
        selected_model = st.selectbox("Select Model", list(st.session_state.models.keys()))
        model          = st.session_state.models[selected_model]
        X_test         = st.session_state.X_test
        y_test         = st.session_state.y_test
        X_test_scaled  = st.session_state.scaler.transform(X_test)

        tab1, tab2, tab3, tab4 = st.tabs([
            "📊 Feature Importance",
            "🔍 SHAP Analysis",
            "📈 Model Diagnostics",
            "💡 Actionable Insights"
        ])

        with tab1:
            st.subheader("Feature Importance Analysis")
            if hasattr(model, 'feature_importances_'):
                # Tree-based models: RF, GB, DT, HistGB
                importance_df = pd.DataFrame({
                    'Feature': st.session_state.feature_names,
                    'Importance': model.feature_importances_
                }).sort_values('Importance', ascending=True)
                fig = px.bar(importance_df.tail(15), x='Importance', y='Feature',
                             orientation='h', title=f'Feature Importance — {selected_model}',
                             color='Importance', color_continuous_scale='Viridis')
                st.plotly_chart(fig, use_container_width=True)

            elif hasattr(model, 'coef_'):
                raw = model.coef_
                arr = np.array(raw)

                # mord.LogisticAT: coef_ is 1D (n_features,) — one weight per feature
                # sklearn LR:      coef_ is 2D (n_classes, n_features)
                if arr.ndim == 1:
                    coefs = np.abs(arr)
                    title = f'|Coefficients| — {selected_model}  (ordinal weights per feature)'
                elif arr.ndim == 2:
                    coefs = np.abs(arr).mean(axis=0)  # mean across classes
                    title = f'Mean |Coefficients| across classes — {selected_model}'
                else:
                    coefs = np.abs(arr).flatten()
                    title = f'|Coefficients| — {selected_model}'

                importance_df = pd.DataFrame({
                    'Feature': st.session_state.feature_names,
                    'Importance': coefs
                }).sort_values('Importance', ascending=True)

                fig = px.bar(importance_df.tail(15), x='Importance', y='Feature',
                             orientation='h', title=title,
                             color='Importance', color_continuous_scale='Viridis')
                st.plotly_chart(fig, use_container_width=True)

                if selected_model == 'Ordinal Logistic Regression':
                    st.caption(
                        "For Ordinal Logistic Regression (mord.LogisticAT), a single coefficient "
                        "per feature is learned under the proportional odds assumption — one weight "
                        "applies consistently across all class boundaries. Features with larger "
                        "|coefficient| values have a stronger effect on the ordinal outcome."
                    )
            else:
                st.info("Feature importance not available for this model type.")

        with tab2:
            st.subheader("SHAP Analysis")
            n_samples    = st.slider("Samples for SHAP", 50, 300, 100)
            max_display  = st.slider("Max features to display", 5, 15, 10)
            analysis_type = st.radio("Plot type", ["Summary Plot", "Feature Importance"], horizontal=True)

            if st.button("🔄 Generate SHAP", type="primary"):
                with st.spinner("Computing SHAP values…"):
                    try:
                        sample_idx = np.random.choice(len(X_test_scaled),
                                                       min(n_samples, len(X_test_scaled)),
                                                       replace=False)
                        X_sample = X_test_scaled[sample_idx]

                        # KernelExplainer works for ALL models universally.
                        # TreeExplainer only supports RF and DT for multiclass —
                        # GradientBoostingClassifier is binary-only in TreeExplainer.
                        # So we use KernelExplainer for everything to avoid all SHAP errors.

                        background = shap.sample(X_sample, min(30, len(X_sample)))
                        predict_fn = (model.predict_proba
                                      if hasattr(model, 'predict_proba')
                                      else model.predict)
                        explainer  = shap.KernelExplainer(predict_fn, background)
                        sv_raw     = explainer.shap_values(X_sample)

                        # ── Normalise SHAP output to always be 2D (samples, features) ──
                        # SHAP can return:
                        #   - a list of arrays (older versions, multiclass): [(s, f), (s, f), ...]
                        #   - a 3D array (newer versions, multiclass):        (s, f, c)
                        #   - a 2D array (binary/regression):                 (s, f)
                        sv_arr = np.array(sv_raw) if isinstance(sv_raw, list) else sv_raw
                        sv_arr = np.abs(sv_arr)

                        n_features = len(st.session_state.feature_names)

                        if sv_arr.ndim == 3:
                            # Shape could be (classes, samples, features) — from list conversion
                            # or (samples, features, classes) — from newer SHAP
                            # Detect by matching n_features to the correct axis
                            if sv_arr.shape[-1] == n_features:
                                # (classes, samples, features) → average over classes
                                sv_2d = sv_arr.mean(axis=0)
                            elif sv_arr.shape[1] == n_features:
                                # (samples, features, classes) → average over classes
                                sv_2d = sv_arr.mean(axis=2)
                            else:
                                # Fallback — flatten last axis
                                sv_2d = sv_arr.mean(axis=-1)
                        elif sv_arr.ndim == 2:
                            sv_2d = sv_arr
                        else:
                            sv_2d = sv_arr.reshape(-1, n_features)

                        # sv_2d is now guaranteed (samples, features)
                        # Get mean absolute SHAP per feature → 1D array of length n_features
                        mean_shap = sv_2d.mean(axis=0).flatten()

                        # Safety check — force 1D and match feature count
                        if len(mean_shap) != n_features:
                            mean_shap = mean_shap[:n_features] if len(mean_shap) > n_features                                         else np.pad(mean_shap, (0, n_features - len(mean_shap)))

                        sv_plot = sv_2d  # for the summary dot plot below

                        feature_shap_df = pd.DataFrame({
                            'Feature': list(st.session_state.feature_names),
                            'Mean |SHAP Value|': list(mean_shap)
                        }).sort_values('Mean |SHAP Value|', ascending=True).tail(max_display)

                        if analysis_type == "Feature Importance":
                            # Bar chart — clean and always works
                            fig_shap = px.bar(
                                feature_shap_df,
                                x='Mean |SHAP Value|',
                                y='Feature',
                                orientation='h',
                                title=f'SHAP Feature Importance — {selected_model}',
                                color='Mean |SHAP Value|',
                                color_continuous_scale='Viridis',
                                text=feature_shap_df['Mean |SHAP Value|'].round(4)
                            )
                            fig_shap.update_traces(textposition='outside')
                            fig_shap.update_layout(height=500)
                            st.plotly_chart(fig_shap, use_container_width=True)

                        else:
                            # Summary dot plot — use matplotlib but with explicit figure passing
                            plt.clf()
                            plt.close('all')
                            fig_shap = plt.figure(figsize=(10, 8))
                            shap.summary_plot(
                                sv_plot,
                                X_sample,
                                feature_names=st.session_state.feature_names,
                                max_display=max_display,
                                plot_type='dot',
                                show=False,
                                plot_size=None
                            )
                            st.pyplot(plt.gcf(), clear_figure=True)
                            plt.close('all')

                        st.caption(
                            f"SHAP values computed using KernelExplainer on {len(X_sample)} test samples. "
                            "Higher values = stronger influence on the prediction. "
                            "GPA and Absences are expected to dominate."
                        )

                    except Exception as e:
                        st.error(f"SHAP error: {str(e)}")
                        st.exception(e)

        with tab3:
            st.subheader("Model Diagnostics")
            y_pred       = model.predict(X_test_scaled)
            y_pred_proba = model.predict_proba(X_test_scaled) if hasattr(model, 'predict_proba') else None

            col1, col2 = st.columns(2)
            with col1:
                cm = confusion_matrix(y_test, y_pred)
                fig = px.imshow(cm,
                                labels=dict(x="Predicted", y="Actual", color="Count"),
                                x=[GRADE_LABELS[i] for i in range(cm.shape[1])],
                                y=[GRADE_LABELS[i] for i in range(cm.shape[0])],
                                color_continuous_scale='Blues',
                                title=f'Confusion Matrix — {selected_model}',
                                text_auto=True)
                st.plotly_chart(fig, use_container_width=True)

            with col2:
                report    = classification_report(y_test, y_pred, output_dict=True)
                rpt_df    = pd.DataFrame(report).transpose()
                class_met = rpt_df.iloc[:-3, :3]
                fig = px.line(class_met, x=class_met.index,
                              y=['precision', 'recall', 'f1-score'],
                              markers=True, title='Metrics by Class',
                              labels={'value': 'Score', 'variable': 'Metric'})
                fig.update_layout(yaxis=dict(range=[0, 1]))
                st.plotly_chart(fig, use_container_width=True)

            if y_pred_proba is not None:
                st.subheader("Multiclass ROC Curves")
                y_test_bin = label_binarize(y_test, classes=sorted(y_test.unique()))
                n_classes  = y_test_bin.shape[1]
                fig        = go.Figure()
                colors     = ['blue', 'red', 'green', 'orange', 'purple']
                for i in range(n_classes):
                    fpr_i, tpr_i, _ = roc_curve(y_test_bin[:, i], y_pred_proba[:, i])
                    auc_i = auc(fpr_i, tpr_i)
                    fig.add_trace(go.Scatter(
                        x=fpr_i, y=tpr_i, mode='lines',
                        line=dict(color=colors[i % len(colors)], width=2),
                        name=f'{GRADE_LABELS[i]} (AUC={auc_i:.2f})'
                    ))
                fig.add_trace(go.Scatter(x=[0, 1], y=[0, 1], mode='lines',
                                         line=dict(color='navy', dash='dash'), showlegend=False))
                fig.update_layout(title='Multiclass ROC Curves',
                                  xaxis_title='False Positive Rate',
                                  yaxis_title='True Positive Rate')
                st.plotly_chart(fig, use_container_width=True)
            else:
                st.info("ROC curves not available for Ordinal Logistic Regression.")

        with tab4:
            st.subheader("Actionable Insights & Recommendations")
            st.markdown("""
            #### 📊 Top Performance Drivers
            1. **GPA** — strongest predictor across all models (importance ~0.45)
            2. **Absences** — high absenteeism strongly correlates with at-risk status
            3. **Parental Support** — moderate but consistent predictor
            4. **Study Time** — positive relationship with GPA and grade class

            #### 🚨 Risk Indicators
            - High absence rates (strong negative predictor)
            - Low parental support levels
            - GPA below 2.0
            - Limited extracurricular engagement

            #### 💡 Intervention Strategies
            **For At-Risk Students (Class 4):**
            - Personalised tutoring programmes
            - Parental involvement initiatives
            - Attendance monitoring and early alert systems

            **For Average Performers (Class 2–3):**
            - Study groups and peer learning
            - Regular progress check-ins
            - Extracurricular activity encouragement
            """)